### ISSUE TITLE
Can't start frontend - Nuxt error modules.config not found

### ISSUE THREAD

**Issue by peterjaap** [ergonode/frontend#499]
## Bug type
Code? Configuration?

## Current behavior
```
$ npm install

.......

$ npm run dev

> ergonode-front@0.9.0 dev /home/peterjaap/development/workspace/ergonode/frontend
> nuxt


 FATAL  Cannot find module './modules.config'                                                                                                                                                              14:08:48
Require stack:
- /home/peterjaap/development/workspace/ergonode/frontend/nuxt.config.js
- /home/peterjaap/development/workspace/ergonode/frontend/node_modules/@nuxt/config/dist/config.js
- /home/peterjaap/development/workspace/ergonode/frontend/node_modules/@nuxt/cli/dist/cli-index.js
- /home/peterjaap/development/workspace/ergonode/frontend/node_modules/@nuxt/cli/dist/cli.js
- /home/peterjaap/development/workspace/ergonode/frontend/node_modules/nuxt/bin/nuxt.js

  Error: Cannot find module './modules.config'
  Require stack:
  - nuxt.config.js
  - node_modules/@nuxt/config/dist/config.js
  - node_modules/@nuxt/cli/dist/cli-index.js
  - node_modules/@nuxt/cli/dist/cli.js
  - node_modules/nuxt/bin/nuxt.js
  at Object.<anonymous> (nuxt.config.js:1)


   ╭────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                        │
   │   ✖ Nuxt Fatal Error                                                                                   │
   │                                                                                                        │
   │   Error: Cannot find module './modules.config'                                                         │
   │   Require stack:                                                                                       │
   │   - /home/peterjaap/development/workspace/ergonode/frontend/nuxt.config.js                             │
   │   - /home/peterjaap/development/workspace/ergonode/frontend/node_modules/@nuxt/config/dist/config.js   │
   │   - /home/peterjaap/development/workspace/ergonode/frontend/node_modules/@nuxt/cli/dist/cli-index.js   │
   │   - /home/peterjaap/development/workspace/ergonode/frontend/node_modules/@nuxt/cli/dist/cli.js         │
   │   - /home/peterjaap/development/workspace/ergonode/frontend/node_modules/nuxt/bin/nuxt.js              │
   │                                                                                                        │
   ╰────────────────────────────────────────────────────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ergonode-front@0.9.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ergonode-front@0.9.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/peterjaap/.npm/_logs/2020-08-31T12_08_48_059Z-debug.log
```

## Expected behavior
It should compile? Start?

## Possible Solution
No idea

## Environment

<pre><code>
Ergonode version: latest

 
Detailed information:
- Node version: 12.8.3  
- Platform:  Ubuntu

Others:
Also tried with yarn, same issue

</code></pre>

**Comment by peterjaap** [comment]
npm log file contents;

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/peterjaap/.nvm/versions/node/v12.18.3/bin/node',
1 verbose cli   '/home/peterjaap/.nvm/versions/node/v12.18.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle ergonode-front@0.9.0~predev: ergonode-front@0.9.0
6 info lifecycle ergonode-front@0.9.0~dev: ergonode-front@0.9.0
7 verbose lifecycle ergonode-front@0.9.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle ergonode-front@0.9.0~dev: PATH: /home/peterjaap/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/peterjaap/development/workspace/ergonode/frontend/node_modules/.bin:/home/peterjaap/.yarn/bin:/home/peterjaap/.config/yarn/global/node_modules/.bin:/home/peterjaap/.yarn/bin:/home/peterjaap/.config/yarn/global/node_modules/.bin:/home/peterjaap/.nvm/versions/node/v12.18.3/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/peterjaap/.local/bin:/home/peterjaap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/peterjaap/development/development/bin:/home/peterjaap/bin/PhpStorm-172.4155.41/bin:/home/peterjaap/.composer/vendor/bin:/home/linuxbrew/.linuxbrew/bin/:/home/peterjaap/.local/bin:/home/peterjaap/development/workspace/peterjaap/connectiq-sdk/bin:/home/peterjaap/development/development/bin:/home/peterjaap/bin/PhpStorm-172.4155.41/bin:/home/peterjaap/.composer/vendor/bin:/home/linuxbrew/.linuxbrew/bin/:/home/peterjaap/.local/bin:/home/peterjaap/development/workspace/peterjaap/connectiq-sdk/bin
9 verbose lifecycle ergonode-front@0.9.0~dev: CWD: /home/peterjaap/development/workspace/ergonode/frontend
10 silly lifecycle ergonode-front@0.9.0~dev: Args: [ '-c', 'nuxt' ]
11 silly lifecycle ergonode-front@0.9.0~dev: Returned: code: 1  signal: null
12 info lifecycle ergonode-front@0.9.0~dev: Failed to exec dev script
13 verbose stack Error: ergonode-front@0.9.0 dev: `nuxt`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/peterjaap/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/peterjaap/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid ergonode-front@0.9.0
15 verbose cwd /home/peterjaap/development/workspace/ergonode/frontend
16 verbose Linux 5.4.0-42-generic
17 verbose argv "/home/peterjaap/.nvm/versions/node/v12.18.3/bin/node" "/home/peterjaap/.nvm/versions/node/v12.18.3/bin/npm" "run" "dev"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error ergonode-front@0.9.0 dev: `nuxt`
22 error Exit status 1
23 error Failed at the ergonode-front@0.9.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by peterjaap** [comment]
Found it, apparently you need to run `npm run modules` first. This was not in the [docs](https://docs.ergonode.com/#/frontend/installation?id=configuration)

**Comment by derpdead** [comment]
@peterjaap thank you for your report! We will update [docs](https://docs.ergonode.com/#/frontend/installation?id=configuration) with or [README](https://github.com/ergonode/frontend/blob/develop/README.md)

**Comment by derpdead** [comment]
@peterjaap here are updated [docs](https://docs.ergonode.com/#/installation/frontend?id=contribution-installation)
